# Generated by Django 6.0.6 on 2026-08-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Image shown on the About Us page', null=True, upload_to='site/'),
        ),
    ]
