# Generated by Django 6.0.7 on 2026-08-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_new_arrival_product_is_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this brand belongs to (e.g. Skincare, Makeup)', related_name='brands', to='products.category'),
        ),
    ]
